# Generated by Django 5.0.3 on 2024-04-15 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_path_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination', to='post.city'),
        ),
        migrations.AddField(
            model_name='service',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin', to='post.city'),
        ),
    ]
